cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-bedeutung/javascripts/eshelper.js 
cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-circle-packed-questionnaires/javascripts/eshelper.js 
cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-context-navigation/javascripts/eshelper.js 
cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-droptheword/javascripts/eshelper.js 
cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-geographical-lemmas/javascripts/eshelper.js 
cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-hierarquical-questionnaire-tree/javascripts/eshelper.js 
cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-organismexplorer/javascripts/eshelper.js 
cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-plants-explorer/javascripts/eshelper.js 
cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-plantwordguruI/javascripts/eshelper.js 
cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-plantwordguru-II/javascripts/eshelper.js 
cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-questionnaire-explorer/javascripts/eshelper.js 
cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-raw-questionnaire-exploration/javascripts/eshelper.js 
cp exploreAT--1word4pics/javascripts/eshelper.js exploreAT-tustep-map/javascripts/eshelper.js 
